### ISSUE TITLE
Trying to see current file order or sort displays "No drive detected"

### ISSUE THREAD

**Issue by cannikin** [lwouis/fat-drive-sorter#6]
**Describe the bug**

When I click either "See current file order" or "Sort" I just get the drive replaced with the text "No drive detected". Then the drive re-appears and I never see any file lists or anything.

**Screenshots / video**

https://github.com/user-attachments/assets/9922e5d2-99c3-48b4-a05d-54fe34bbea33

**Steps to reproduce the bug**

1. Insert an SD card
2. Click on "See current file order"
3. See error

**Your environment**

* FatDriveSorter version: 1.1.2
* macOS version: 15.1.1
* Other relevant info: 

<img width="660" alt="image" src="https://github.com/user-attachments/assets/cda95b67-31df-417e-a906-5de000d34862">

**Comment by lwouis** [comment]
Hi,

In order to list or sort, the app has to unmount the drive, run `fastsort`, then remount the drive. This is because `fatsort` can only operate on unmounted drives.

This explains the disk coming in and out. This doesn't explain the empty list after you click on the button.

Could you please run the app from Terminal.app, and share the output when you click the button here?

`/Applications/FatDriveSorter.app/Contents/MacOS/FatDriveSorter`

Thank you

**Comment by cannikin** [comment]
Same thing: the first time I click one of the buttons I'm asked for my password, then it flashes the unmount message, then comes back, but no file list. :( There are definitely files in there, though!

<img width="925" alt="image" src="https://github.com/user-attachments/assets/3bff83fd-a15f-4821-8a50-d43aa2883418">

Is there a debug mode I can enable, or tail some logs somewhere?

**Comment by lwouis** [comment]
Thank you?

if you run the app from the Terminal as i've shown above, it will output logs. Those logs may show clues as to why there is no listing

**Comment by cannikin** [comment]
Okay opened with `open /Applications/FatDriveSorter.app --stderr /tmp/file.log` to get some output and ended up with:

```
2024-12-08 13:57:20.204 FatDriveSorter[44707:2370681] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-08 13:57:20.204 FatDriveSorter[44707:2370681] +[IMKInputSession subclass]: chose IMKInputSession_Modern
openFileSystem: Filesystem is mounted. Please unmount!
sortFileSystem: Failed to open file system!
main: Failed to sort file system!
```

It repeats those last 3 lines whenever I click either button.

**Comment by lwouis** [comment]
Thank you for your message

From the logs you shared, it seems that `fatsort` can't operate, because the filesystem is still mounted. This is surprising since the drive looks to properly be unmounted (see your video).

I've create this [local build which waits 5s after the unmount](https://github.com/user-attachments/files/18060152/FatDriveSorter.zip), before calling `fatsort`. Could you please try it out?

Thank you 🙇

**Comment by cannikin** [comment]
Okay, same behavior in the app itself (5 second delay before asking me for password), but a different message in the logs now:

```
2024-12-09 22:02:08.052 FatDriveSorter[83007:3086093] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-09 22:02:08.052 FatDriveSorter[83007:3086093] +[IMKInputSession subclass]: chose IMKInputSession_Modern
sortFileSystem: FATs don't match! Please repair file system!
main: Failed to sort file system!
```

Clicking either button results in a 5 second delay and then the same last two lines of the log repeat.

I ran First Aid in Disk Utility and it output:

```
Running First Aid on “EVERDRIVE” (disk6s1)

Checking file system and repairing if necessary and if possible.
Volume was successfully unmounted.
Performing fsck_msdos -y /dev/rdisk6s1
** /dev/rdisk6s1

** Phase 1 - Preparing FAT

** Phase 2 - Checking Directories

** Phase 3 - Checking for Orphan Clusters

Warning: 230 files, 31159328 KiB free (973729 clusters)

File system check exit code is 0.
Restoring the original state found as mounted.

Operation successful.
```

Just to doublecheck, went back to FileSorter, but got the same output.

I *am* able to run a file sorter utility on a Windows machine and it had no problem sorting the files.

**Comment by lwouis** [comment]
I think the path forward is to backup the files, then reformat your drive. Move your files back onto it. And use FatDriveSorter again.

Hopefully it works then

**Comment by cannikin** [comment]
It worked! Thanks so much for the help, sorry it ended up being a wild goose chase! :)

**Comment by lwouis** [comment]
I'm glad you got it to work. It's a great feeling to get the files to be sorted on these devices 🎉
